# docker-compose -f docker-compose.yaml up --build --remove-orphans

version: '3.8'

services:
 tempdb:
  build:
   context: .
  ports:
  - 8888:5000

###
version: '3.8'

services:
 tempdb:
  image: cenzwong/flask-tools:latest
   context: .
  ports:
  - 8888:5000
